services:
  nest-starter-api:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    container_name: nest-starter-api-dev-con
    image: nest-starter-api:dev
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./.env.development
    volumes:
      - .:/workspace
      - /workspace/node_modules
