version: '3.9'
services:
  nest-template-api:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    container_name: nest-template-api-dev-con
    image: nest-template-api:dev
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env.development
    volumes:
      - .:/app
      - /app/node_modules
